### ISSUE TITLE
database

### ISSUE THREAD

**Issue by cheuk3** [poulainv/tottem#127]
What database does this project use? 
Postgresql on your server?

**Comment by poulainv** [comment]
Hi, @cheuk3 I am using a RDS postgresql database.

**Comment by cheuk3** [comment]
Aws rds? May I know the cost?

**Comment by poulainv** [comment]
Of course, every thing is available here https://aws.amazon.com/rds/pricing/ Note that they provide a free tier as well

**Comment by michael-land** [comment]
@poulainv  Will each request open a new dB connection? Any idea how to share connections between requests?

**Comment by poulainv** [comment]
@xiaoyu-tamu Depending on your infrastructure. There is some best practice with prisma [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/deployment#serverless-faas). Container reuse works well on Vercel for instance
